"use client";

import { useState, useTransition } from "react";
import { generateShiftDigest } from "@/app/agents/shift-digest/actions";

type Result = Awaited<ReturnType<typeof generateShiftDigest>>;

export default function DigestPanel({
  date,
  shift,
  line,
}: {
  date: string;
  shift: "AM" | "PM";
  line: string;
}) {
  const [result, setResult] = useState<Result | null>(null);
  const [isPending, startTransition] = useTransition();

  function handleGenerate() {
    startTransition(async () => {
      const r = await generateShiftDigest(date, shift, line);
      setResult(r);
    });
  }

  return (
    <div className="rounded-lg border border-[var(--color-border)] bg-white p-5">
      <div className="flex items-center justify-between gap-3">
        <div>
          <p className="text-xs uppercase tracking-wide text-slate-400">
            {date} &middot; {shift} &middot; {line}
          </p>
        </div>
        <button
          onClick={handleGenerate}
          disabled={isPending}
          className="rounded-full bg-[var(--color-accent)] px-4 py-1.5 text-xs font-semibold text-white transition hover:brightness-95 disabled:opacity-50"
        >
          {isPending ? "Generating…" : result ? "Regenerate digest" : "Generate digest"}
        </button>
      </div>

      {result && (
        <div className="mt-4 space-y-4">
          <p className="rounded-md bg-slate-50 p-4 text-sm leading-relaxed text-[var(--color-navy)]">
            {result.digest}
          </p>
          <p className="text-[11px] text-slate-400">
            {result.usedModel
              ? "Generated by Claude from the shift data below — a starting draft for you to verify, not a final report."
              : "Template draft — set ANTHROPIC_API_KEY to enable the live narrative agent."}
          </p>

          <details className="rounded-md border border-[var(--color-border)] p-3 text-xs text-slate-500">
            <summary className="cursor-pointer font-medium text-slate-600">
              Underlying shift data ({result.summary.runs.length} runs, {result.summary.flags.length} flagged)
            </summary>
            <div className="mt-3 space-y-2">
              {result.summary.runs.map((r) => (
                <div key={r.run.id} className="flex justify-between">
                  <span className="capitalize">{r.run.species}</span>
                  <span className={r.withinTolerance ? "text-slate-400" : "font-medium text-amber-700"}>
                    {(r.actualYieldPct * 100).toFixed(1)}% vs {(r.expectedYieldPct * 100).toFixed(1)}% target
                  </span>
                </div>
              ))}
              {result.summary.qcHolds.map((h, i) => (
                <div key={i} className="flex justify-between">
                  <span>QC hold &middot; {h.species}</span>
                  <span>{h.resolved ? "resolved" : "open"}</span>
                </div>
              ))}
              <div className="flex justify-between">
                <span>Downtime</span>
                <span>{result.summary.downtimeMinutes} min</span>
              </div>
              {result.summary.staffing && (
                <div className="flex justify-between">
                  <span>Staffing</span>
                  <span>
                    {result.summary.staffing.actual}/{result.summary.staffing.scheduled} scheduled,{" "}
                    {result.summary.staffing.overtimeHours}h OT
                  </span>
                </div>
              )}
            </div>
          </details>
        </div>
      )}
    </div>
  );
}
